# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.CharField(default='no value', max_length=45),
            preserve_default=False,
        ),
    ]
